// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CertificateDataV1.proto

package org.medibloc.phr;

public final class CertificateDataV1 {
  private CertificateDataV1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CertificateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Certificate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 version = 1;</code>
     */
    int getVersion();

    /**
     * <code>string blockchain_address = 2;</code>
     */
    java.lang.String getBlockchainAddress();
    /**
     * <code>string blockchain_address = 2;</code>
     */
    com.google.protobuf.ByteString
        getBlockchainAddressBytes();

    /**
     * <code>.Certification certification = 3;</code>
     */
    boolean hasCertification();
    /**
     * <code>.Certification certification = 3;</code>
     */
    org.medibloc.phr.CertificateDataV1.Certification getCertification();
    /**
     * <code>.Certification certification = 3;</code>
     */
    org.medibloc.phr.CertificateDataV1.CertificationOrBuilder getCertificationOrBuilder();
  }
  /**
   * Protobuf type {@code Certificate}
   */
  public  static final class Certificate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Certificate)
      CertificateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Certificate.newBuilder() to construct.
    private Certificate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Certificate() {
      version_ = 0;
      blockchainAddress_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Certificate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              version_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              blockchainAddress_ = s;
              break;
            }
            case 26: {
              org.medibloc.phr.CertificateDataV1.Certification.Builder subBuilder = null;
              if (certification_ != null) {
                subBuilder = certification_.toBuilder();
              }
              certification_ = input.readMessage(org.medibloc.phr.CertificateDataV1.Certification.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(certification_);
                certification_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.medibloc.phr.CertificateDataV1.internal_static_Certificate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.medibloc.phr.CertificateDataV1.internal_static_Certificate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.medibloc.phr.CertificateDataV1.Certificate.class, org.medibloc.phr.CertificateDataV1.Certificate.Builder.class);
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>uint32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int BLOCKCHAIN_ADDRESS_FIELD_NUMBER = 2;
    private volatile java.lang.Object blockchainAddress_;
    /**
     * <code>string blockchain_address = 2;</code>
     */
    public java.lang.String getBlockchainAddress() {
      java.lang.Object ref = blockchainAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        blockchainAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string blockchain_address = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBlockchainAddressBytes() {
      java.lang.Object ref = blockchainAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        blockchainAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CERTIFICATION_FIELD_NUMBER = 3;
    private org.medibloc.phr.CertificateDataV1.Certification certification_;
    /**
     * <code>.Certification certification = 3;</code>
     */
    public boolean hasCertification() {
      return certification_ != null;
    }
    /**
     * <code>.Certification certification = 3;</code>
     */
    public org.medibloc.phr.CertificateDataV1.Certification getCertification() {
      return certification_ == null ? org.medibloc.phr.CertificateDataV1.Certification.getDefaultInstance() : certification_;
    }
    /**
     * <code>.Certification certification = 3;</code>
     */
    public org.medibloc.phr.CertificateDataV1.CertificationOrBuilder getCertificationOrBuilder() {
      return getCertification();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (version_ != 0) {
        output.writeUInt32(1, version_);
      }
      if (!getBlockchainAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, blockchainAddress_);
      }
      if (certification_ != null) {
        output.writeMessage(3, getCertification());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, version_);
      }
      if (!getBlockchainAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, blockchainAddress_);
      }
      if (certification_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getCertification());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.medibloc.phr.CertificateDataV1.Certificate)) {
        return super.equals(obj);
      }
      org.medibloc.phr.CertificateDataV1.Certificate other = (org.medibloc.phr.CertificateDataV1.Certificate) obj;

      boolean result = true;
      result = result && (getVersion()
          == other.getVersion());
      result = result && getBlockchainAddress()
          .equals(other.getBlockchainAddress());
      result = result && (hasCertification() == other.hasCertification());
      if (hasCertification()) {
        result = result && getCertification()
            .equals(other.getCertification());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + BLOCKCHAIN_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getBlockchainAddress().hashCode();
      if (hasCertification()) {
        hash = (37 * hash) + CERTIFICATION_FIELD_NUMBER;
        hash = (53 * hash) + getCertification().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.medibloc.phr.CertificateDataV1.Certificate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.medibloc.phr.CertificateDataV1.Certificate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.medibloc.phr.CertificateDataV1.Certificate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.medibloc.phr.CertificateDataV1.Certificate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.medibloc.phr.CertificateDataV1.Certificate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.medibloc.phr.CertificateDataV1.Certificate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.medibloc.phr.CertificateDataV1.Certificate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.medibloc.phr.CertificateDataV1.Certificate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.medibloc.phr.CertificateDataV1.Certificate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.medibloc.phr.CertificateDataV1.Certificate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.medibloc.phr.CertificateDataV1.Certificate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.medibloc.phr.CertificateDataV1.Certificate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.medibloc.phr.CertificateDataV1.Certificate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Certificate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Certificate)
        org.medibloc.phr.CertificateDataV1.CertificateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.medibloc.phr.CertificateDataV1.internal_static_Certificate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.medibloc.phr.CertificateDataV1.internal_static_Certificate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.medibloc.phr.CertificateDataV1.Certificate.class, org.medibloc.phr.CertificateDataV1.Certificate.Builder.class);
      }

      // Construct using org.medibloc.phr.CertificateDataV1.Certificate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0;

        blockchainAddress_ = "";

        if (certificationBuilder_ == null) {
          certification_ = null;
        } else {
          certification_ = null;
          certificationBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.medibloc.phr.CertificateDataV1.internal_static_Certificate_descriptor;
      }

      @java.lang.Override
      public org.medibloc.phr.CertificateDataV1.Certificate getDefaultInstanceForType() {
        return org.medibloc.phr.CertificateDataV1.Certificate.getDefaultInstance();
      }

      @java.lang.Override
      public org.medibloc.phr.CertificateDataV1.Certificate build() {
        org.medibloc.phr.CertificateDataV1.Certificate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.medibloc.phr.CertificateDataV1.Certificate buildPartial() {
        org.medibloc.phr.CertificateDataV1.Certificate result = new org.medibloc.phr.CertificateDataV1.Certificate(this);
        result.version_ = version_;
        result.blockchainAddress_ = blockchainAddress_;
        if (certificationBuilder_ == null) {
          result.certification_ = certification_;
        } else {
          result.certification_ = certificationBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.medibloc.phr.CertificateDataV1.Certificate) {
          return mergeFrom((org.medibloc.phr.CertificateDataV1.Certificate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.medibloc.phr.CertificateDataV1.Certificate other) {
        if (other == org.medibloc.phr.CertificateDataV1.Certificate.getDefaultInstance()) return this;
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (!other.getBlockchainAddress().isEmpty()) {
          blockchainAddress_ = other.blockchainAddress_;
          onChanged();
        }
        if (other.hasCertification()) {
          mergeCertification(other.getCertification());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.medibloc.phr.CertificateDataV1.Certificate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.medibloc.phr.CertificateDataV1.Certificate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int version_ ;
      /**
       * <code>uint32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>uint32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 version = 1;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object blockchainAddress_ = "";
      /**
       * <code>string blockchain_address = 2;</code>
       */
      public java.lang.String getBlockchainAddress() {
        java.lang.Object ref = blockchainAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          blockchainAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string blockchain_address = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBlockchainAddressBytes() {
        java.lang.Object ref = blockchainAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          blockchainAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string blockchain_address = 2;</code>
       */
      public Builder setBlockchainAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        blockchainAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string blockchain_address = 2;</code>
       */
      public Builder clearBlockchainAddress() {
        
        blockchainAddress_ = getDefaultInstance().getBlockchainAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string blockchain_address = 2;</code>
       */
      public Builder setBlockchainAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        blockchainAddress_ = value;
        onChanged();
        return this;
      }

      private org.medibloc.phr.CertificateDataV1.Certification certification_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.medibloc.phr.CertificateDataV1.Certification, org.medibloc.phr.CertificateDataV1.Certification.Builder, org.medibloc.phr.CertificateDataV1.CertificationOrBuilder> certificationBuilder_;
      /**
       * <code>.Certification certification = 3;</code>
       */
      public boolean hasCertification() {
        return certificationBuilder_ != null || certification_ != null;
      }
      /**
       * <code>.Certification certification = 3;</code>
       */
      public org.medibloc.phr.CertificateDataV1.Certification getCertification() {
        if (certificationBuilder_ == null) {
          return certification_ == null ? org.medibloc.phr.CertificateDataV1.Certification.getDefaultInstance() : certification_;
        } else {
          return certificationBuilder_.getMessage();
        }
      }
      /**
       * <code>.Certification certification = 3;</code>
       */
      public Builder setCertification(org.medibloc.phr.CertificateDataV1.Certification value) {
        if (certificationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          certification_ = value;
          onChanged();
        } else {
          certificationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Certification certification = 3;</code>
       */
      public Builder setCertification(
          org.medibloc.phr.CertificateDataV1.Certification.Builder builderForValue) {
        if (certificationBuilder_ == null) {
          certification_ = builderForValue.build();
          onChanged();
        } else {
          certificationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Certification certification = 3;</code>
       */
      public Builder mergeCertification(org.medibloc.phr.CertificateDataV1.Certification value) {
        if (certificationBuilder_ == null) {
          if (certification_ != null) {
            certification_ =
              org.medibloc.phr.CertificateDataV1.Certification.newBuilder(certification_).mergeFrom(value).buildPartial();
          } else {
            certification_ = value;
          }
          onChanged();
        } else {
          certificationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Certification certification = 3;</code>
       */
      public Builder clearCertification() {
        if (certificationBuilder_ == null) {
          certification_ = null;
          onChanged();
        } else {
          certification_ = null;
          certificationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Certification certification = 3;</code>
       */
      public org.medibloc.phr.CertificateDataV1.Certification.Builder getCertificationBuilder() {
        
        onChanged();
        return getCertificationFieldBuilder().getBuilder();
      }
      /**
       * <code>.Certification certification = 3;</code>
       */
      public org.medibloc.phr.CertificateDataV1.CertificationOrBuilder getCertificationOrBuilder() {
        if (certificationBuilder_ != null) {
          return certificationBuilder_.getMessageOrBuilder();
        } else {
          return certification_ == null ?
              org.medibloc.phr.CertificateDataV1.Certification.getDefaultInstance() : certification_;
        }
      }
      /**
       * <code>.Certification certification = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.medibloc.phr.CertificateDataV1.Certification, org.medibloc.phr.CertificateDataV1.Certification.Builder, org.medibloc.phr.CertificateDataV1.CertificationOrBuilder> 
          getCertificationFieldBuilder() {
        if (certificationBuilder_ == null) {
          certificationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.medibloc.phr.CertificateDataV1.Certification, org.medibloc.phr.CertificateDataV1.Certification.Builder, org.medibloc.phr.CertificateDataV1.CertificationOrBuilder>(
                  getCertification(),
                  getParentForChildren(),
                  isClean());
          certification_ = null;
        }
        return certificationBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Certificate)
    }

    // @@protoc_insertion_point(class_scope:Certificate)
    private static final org.medibloc.phr.CertificateDataV1.Certificate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.medibloc.phr.CertificateDataV1.Certificate();
    }

    public static org.medibloc.phr.CertificateDataV1.Certificate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Certificate>
        PARSER = new com.google.protobuf.AbstractParser<Certificate>() {
      @java.lang.Override
      public Certificate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Certificate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Certificate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Certificate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.medibloc.phr.CertificateDataV1.Certificate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CertificationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Certification)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string certification_result = 1;</code>
     */
    java.lang.String getCertificationResult();
    /**
     * <code>string certification_result = 1;</code>
     */
    com.google.protobuf.ByteString
        getCertificationResultBytes();

    /**
     * <code>string person_name = 2;</code>
     */
    java.lang.String getPersonName();
    /**
     * <code>string person_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getPersonNameBytes();

    /**
     * <code>string person_birthdate = 3;</code>
     */
    java.lang.String getPersonBirthdate();
    /**
     * <code>string person_birthdate = 3;</code>
     */
    com.google.protobuf.ByteString
        getPersonBirthdateBytes();

    /**
     * <code>string person_gender = 4;</code>
     */
    java.lang.String getPersonGender();
    /**
     * <code>string person_gender = 4;</code>
     */
    com.google.protobuf.ByteString
        getPersonGenderBytes();

    /**
     * <code>string person_nation = 5;</code>
     */
    java.lang.String getPersonNation();
    /**
     * <code>string person_nation = 5;</code>
     */
    com.google.protobuf.ByteString
        getPersonNationBytes();

    /**
     * <code>string person_ci = 6;</code>
     */
    java.lang.String getPersonCi();
    /**
     * <code>string person_ci = 6;</code>
     */
    com.google.protobuf.ByteString
        getPersonCiBytes();

    /**
     * <code>string person_mobile_company = 7;</code>
     */
    java.lang.String getPersonMobileCompany();
    /**
     * <code>string person_mobile_company = 7;</code>
     */
    com.google.protobuf.ByteString
        getPersonMobileCompanyBytes();

    /**
     * <code>string person_mobile_number = 8;</code>
     */
    java.lang.String getPersonMobileNumber();
    /**
     * <code>string person_mobile_number = 8;</code>
     */
    com.google.protobuf.ByteString
        getPersonMobileNumberBytes();
  }
  /**
   * Protobuf type {@code Certification}
   */
  public  static final class Certification extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Certification)
      CertificationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Certification.newBuilder() to construct.
    private Certification(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Certification() {
      certificationResult_ = "";
      personName_ = "";
      personBirthdate_ = "";
      personGender_ = "";
      personNation_ = "";
      personCi_ = "";
      personMobileCompany_ = "";
      personMobileNumber_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Certification(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              certificationResult_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              personName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              personBirthdate_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              personGender_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              personNation_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              personCi_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              personMobileCompany_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              personMobileNumber_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.medibloc.phr.CertificateDataV1.internal_static_Certification_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.medibloc.phr.CertificateDataV1.internal_static_Certification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.medibloc.phr.CertificateDataV1.Certification.class, org.medibloc.phr.CertificateDataV1.Certification.Builder.class);
    }

    public static final int CERTIFICATION_RESULT_FIELD_NUMBER = 1;
    private volatile java.lang.Object certificationResult_;
    /**
     * <code>string certification_result = 1;</code>
     */
    public java.lang.String getCertificationResult() {
      java.lang.Object ref = certificationResult_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        certificationResult_ = s;
        return s;
      }
    }
    /**
     * <code>string certification_result = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCertificationResultBytes() {
      java.lang.Object ref = certificationResult_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        certificationResult_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PERSON_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object personName_;
    /**
     * <code>string person_name = 2;</code>
     */
    public java.lang.String getPersonName() {
      java.lang.Object ref = personName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        personName_ = s;
        return s;
      }
    }
    /**
     * <code>string person_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPersonNameBytes() {
      java.lang.Object ref = personName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        personName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PERSON_BIRTHDATE_FIELD_NUMBER = 3;
    private volatile java.lang.Object personBirthdate_;
    /**
     * <code>string person_birthdate = 3;</code>
     */
    public java.lang.String getPersonBirthdate() {
      java.lang.Object ref = personBirthdate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        personBirthdate_ = s;
        return s;
      }
    }
    /**
     * <code>string person_birthdate = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPersonBirthdateBytes() {
      java.lang.Object ref = personBirthdate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        personBirthdate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PERSON_GENDER_FIELD_NUMBER = 4;
    private volatile java.lang.Object personGender_;
    /**
     * <code>string person_gender = 4;</code>
     */
    public java.lang.String getPersonGender() {
      java.lang.Object ref = personGender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        personGender_ = s;
        return s;
      }
    }
    /**
     * <code>string person_gender = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPersonGenderBytes() {
      java.lang.Object ref = personGender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        personGender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PERSON_NATION_FIELD_NUMBER = 5;
    private volatile java.lang.Object personNation_;
    /**
     * <code>string person_nation = 5;</code>
     */
    public java.lang.String getPersonNation() {
      java.lang.Object ref = personNation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        personNation_ = s;
        return s;
      }
    }
    /**
     * <code>string person_nation = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPersonNationBytes() {
      java.lang.Object ref = personNation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        personNation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PERSON_CI_FIELD_NUMBER = 6;
    private volatile java.lang.Object personCi_;
    /**
     * <code>string person_ci = 6;</code>
     */
    public java.lang.String getPersonCi() {
      java.lang.Object ref = personCi_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        personCi_ = s;
        return s;
      }
    }
    /**
     * <code>string person_ci = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPersonCiBytes() {
      java.lang.Object ref = personCi_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        personCi_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PERSON_MOBILE_COMPANY_FIELD_NUMBER = 7;
    private volatile java.lang.Object personMobileCompany_;
    /**
     * <code>string person_mobile_company = 7;</code>
     */
    public java.lang.String getPersonMobileCompany() {
      java.lang.Object ref = personMobileCompany_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        personMobileCompany_ = s;
        return s;
      }
    }
    /**
     * <code>string person_mobile_company = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPersonMobileCompanyBytes() {
      java.lang.Object ref = personMobileCompany_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        personMobileCompany_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PERSON_MOBILE_NUMBER_FIELD_NUMBER = 8;
    private volatile java.lang.Object personMobileNumber_;
    /**
     * <code>string person_mobile_number = 8;</code>
     */
    public java.lang.String getPersonMobileNumber() {
      java.lang.Object ref = personMobileNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        personMobileNumber_ = s;
        return s;
      }
    }
    /**
     * <code>string person_mobile_number = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPersonMobileNumberBytes() {
      java.lang.Object ref = personMobileNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        personMobileNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCertificationResultBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, certificationResult_);
      }
      if (!getPersonNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, personName_);
      }
      if (!getPersonBirthdateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, personBirthdate_);
      }
      if (!getPersonGenderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, personGender_);
      }
      if (!getPersonNationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, personNation_);
      }
      if (!getPersonCiBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, personCi_);
      }
      if (!getPersonMobileCompanyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, personMobileCompany_);
      }
      if (!getPersonMobileNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, personMobileNumber_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCertificationResultBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, certificationResult_);
      }
      if (!getPersonNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, personName_);
      }
      if (!getPersonBirthdateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, personBirthdate_);
      }
      if (!getPersonGenderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, personGender_);
      }
      if (!getPersonNationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, personNation_);
      }
      if (!getPersonCiBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, personCi_);
      }
      if (!getPersonMobileCompanyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, personMobileCompany_);
      }
      if (!getPersonMobileNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, personMobileNumber_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.medibloc.phr.CertificateDataV1.Certification)) {
        return super.equals(obj);
      }
      org.medibloc.phr.CertificateDataV1.Certification other = (org.medibloc.phr.CertificateDataV1.Certification) obj;

      boolean result = true;
      result = result && getCertificationResult()
          .equals(other.getCertificationResult());
      result = result && getPersonName()
          .equals(other.getPersonName());
      result = result && getPersonBirthdate()
          .equals(other.getPersonBirthdate());
      result = result && getPersonGender()
          .equals(other.getPersonGender());
      result = result && getPersonNation()
          .equals(other.getPersonNation());
      result = result && getPersonCi()
          .equals(other.getPersonCi());
      result = result && getPersonMobileCompany()
          .equals(other.getPersonMobileCompany());
      result = result && getPersonMobileNumber()
          .equals(other.getPersonMobileNumber());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CERTIFICATION_RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getCertificationResult().hashCode();
      hash = (37 * hash) + PERSON_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getPersonName().hashCode();
      hash = (37 * hash) + PERSON_BIRTHDATE_FIELD_NUMBER;
      hash = (53 * hash) + getPersonBirthdate().hashCode();
      hash = (37 * hash) + PERSON_GENDER_FIELD_NUMBER;
      hash = (53 * hash) + getPersonGender().hashCode();
      hash = (37 * hash) + PERSON_NATION_FIELD_NUMBER;
      hash = (53 * hash) + getPersonNation().hashCode();
      hash = (37 * hash) + PERSON_CI_FIELD_NUMBER;
      hash = (53 * hash) + getPersonCi().hashCode();
      hash = (37 * hash) + PERSON_MOBILE_COMPANY_FIELD_NUMBER;
      hash = (53 * hash) + getPersonMobileCompany().hashCode();
      hash = (37 * hash) + PERSON_MOBILE_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPersonMobileNumber().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.medibloc.phr.CertificateDataV1.Certification parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.medibloc.phr.CertificateDataV1.Certification parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.medibloc.phr.CertificateDataV1.Certification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.medibloc.phr.CertificateDataV1.Certification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.medibloc.phr.CertificateDataV1.Certification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.medibloc.phr.CertificateDataV1.Certification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.medibloc.phr.CertificateDataV1.Certification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.medibloc.phr.CertificateDataV1.Certification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.medibloc.phr.CertificateDataV1.Certification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.medibloc.phr.CertificateDataV1.Certification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.medibloc.phr.CertificateDataV1.Certification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.medibloc.phr.CertificateDataV1.Certification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.medibloc.phr.CertificateDataV1.Certification prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Certification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Certification)
        org.medibloc.phr.CertificateDataV1.CertificationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.medibloc.phr.CertificateDataV1.internal_static_Certification_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.medibloc.phr.CertificateDataV1.internal_static_Certification_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.medibloc.phr.CertificateDataV1.Certification.class, org.medibloc.phr.CertificateDataV1.Certification.Builder.class);
      }

      // Construct using org.medibloc.phr.CertificateDataV1.Certification.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        certificationResult_ = "";

        personName_ = "";

        personBirthdate_ = "";

        personGender_ = "";

        personNation_ = "";

        personCi_ = "";

        personMobileCompany_ = "";

        personMobileNumber_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.medibloc.phr.CertificateDataV1.internal_static_Certification_descriptor;
      }

      @java.lang.Override
      public org.medibloc.phr.CertificateDataV1.Certification getDefaultInstanceForType() {
        return org.medibloc.phr.CertificateDataV1.Certification.getDefaultInstance();
      }

      @java.lang.Override
      public org.medibloc.phr.CertificateDataV1.Certification build() {
        org.medibloc.phr.CertificateDataV1.Certification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.medibloc.phr.CertificateDataV1.Certification buildPartial() {
        org.medibloc.phr.CertificateDataV1.Certification result = new org.medibloc.phr.CertificateDataV1.Certification(this);
        result.certificationResult_ = certificationResult_;
        result.personName_ = personName_;
        result.personBirthdate_ = personBirthdate_;
        result.personGender_ = personGender_;
        result.personNation_ = personNation_;
        result.personCi_ = personCi_;
        result.personMobileCompany_ = personMobileCompany_;
        result.personMobileNumber_ = personMobileNumber_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.medibloc.phr.CertificateDataV1.Certification) {
          return mergeFrom((org.medibloc.phr.CertificateDataV1.Certification)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.medibloc.phr.CertificateDataV1.Certification other) {
        if (other == org.medibloc.phr.CertificateDataV1.Certification.getDefaultInstance()) return this;
        if (!other.getCertificationResult().isEmpty()) {
          certificationResult_ = other.certificationResult_;
          onChanged();
        }
        if (!other.getPersonName().isEmpty()) {
          personName_ = other.personName_;
          onChanged();
        }
        if (!other.getPersonBirthdate().isEmpty()) {
          personBirthdate_ = other.personBirthdate_;
          onChanged();
        }
        if (!other.getPersonGender().isEmpty()) {
          personGender_ = other.personGender_;
          onChanged();
        }
        if (!other.getPersonNation().isEmpty()) {
          personNation_ = other.personNation_;
          onChanged();
        }
        if (!other.getPersonCi().isEmpty()) {
          personCi_ = other.personCi_;
          onChanged();
        }
        if (!other.getPersonMobileCompany().isEmpty()) {
          personMobileCompany_ = other.personMobileCompany_;
          onChanged();
        }
        if (!other.getPersonMobileNumber().isEmpty()) {
          personMobileNumber_ = other.personMobileNumber_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.medibloc.phr.CertificateDataV1.Certification parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.medibloc.phr.CertificateDataV1.Certification) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object certificationResult_ = "";
      /**
       * <code>string certification_result = 1;</code>
       */
      public java.lang.String getCertificationResult() {
        java.lang.Object ref = certificationResult_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          certificationResult_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string certification_result = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCertificationResultBytes() {
        java.lang.Object ref = certificationResult_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          certificationResult_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string certification_result = 1;</code>
       */
      public Builder setCertificationResult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        certificationResult_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string certification_result = 1;</code>
       */
      public Builder clearCertificationResult() {
        
        certificationResult_ = getDefaultInstance().getCertificationResult();
        onChanged();
        return this;
      }
      /**
       * <code>string certification_result = 1;</code>
       */
      public Builder setCertificationResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        certificationResult_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object personName_ = "";
      /**
       * <code>string person_name = 2;</code>
       */
      public java.lang.String getPersonName() {
        java.lang.Object ref = personName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          personName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string person_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPersonNameBytes() {
        java.lang.Object ref = personName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          personName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string person_name = 2;</code>
       */
      public Builder setPersonName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        personName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string person_name = 2;</code>
       */
      public Builder clearPersonName() {
        
        personName_ = getDefaultInstance().getPersonName();
        onChanged();
        return this;
      }
      /**
       * <code>string person_name = 2;</code>
       */
      public Builder setPersonNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        personName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object personBirthdate_ = "";
      /**
       * <code>string person_birthdate = 3;</code>
       */
      public java.lang.String getPersonBirthdate() {
        java.lang.Object ref = personBirthdate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          personBirthdate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string person_birthdate = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPersonBirthdateBytes() {
        java.lang.Object ref = personBirthdate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          personBirthdate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string person_birthdate = 3;</code>
       */
      public Builder setPersonBirthdate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        personBirthdate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string person_birthdate = 3;</code>
       */
      public Builder clearPersonBirthdate() {
        
        personBirthdate_ = getDefaultInstance().getPersonBirthdate();
        onChanged();
        return this;
      }
      /**
       * <code>string person_birthdate = 3;</code>
       */
      public Builder setPersonBirthdateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        personBirthdate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object personGender_ = "";
      /**
       * <code>string person_gender = 4;</code>
       */
      public java.lang.String getPersonGender() {
        java.lang.Object ref = personGender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          personGender_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string person_gender = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPersonGenderBytes() {
        java.lang.Object ref = personGender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          personGender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string person_gender = 4;</code>
       */
      public Builder setPersonGender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        personGender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string person_gender = 4;</code>
       */
      public Builder clearPersonGender() {
        
        personGender_ = getDefaultInstance().getPersonGender();
        onChanged();
        return this;
      }
      /**
       * <code>string person_gender = 4;</code>
       */
      public Builder setPersonGenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        personGender_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object personNation_ = "";
      /**
       * <code>string person_nation = 5;</code>
       */
      public java.lang.String getPersonNation() {
        java.lang.Object ref = personNation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          personNation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string person_nation = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPersonNationBytes() {
        java.lang.Object ref = personNation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          personNation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string person_nation = 5;</code>
       */
      public Builder setPersonNation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        personNation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string person_nation = 5;</code>
       */
      public Builder clearPersonNation() {
        
        personNation_ = getDefaultInstance().getPersonNation();
        onChanged();
        return this;
      }
      /**
       * <code>string person_nation = 5;</code>
       */
      public Builder setPersonNationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        personNation_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object personCi_ = "";
      /**
       * <code>string person_ci = 6;</code>
       */
      public java.lang.String getPersonCi() {
        java.lang.Object ref = personCi_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          personCi_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string person_ci = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPersonCiBytes() {
        java.lang.Object ref = personCi_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          personCi_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string person_ci = 6;</code>
       */
      public Builder setPersonCi(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        personCi_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string person_ci = 6;</code>
       */
      public Builder clearPersonCi() {
        
        personCi_ = getDefaultInstance().getPersonCi();
        onChanged();
        return this;
      }
      /**
       * <code>string person_ci = 6;</code>
       */
      public Builder setPersonCiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        personCi_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object personMobileCompany_ = "";
      /**
       * <code>string person_mobile_company = 7;</code>
       */
      public java.lang.String getPersonMobileCompany() {
        java.lang.Object ref = personMobileCompany_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          personMobileCompany_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string person_mobile_company = 7;</code>
       */
      public com.google.protobuf.ByteString
          getPersonMobileCompanyBytes() {
        java.lang.Object ref = personMobileCompany_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          personMobileCompany_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string person_mobile_company = 7;</code>
       */
      public Builder setPersonMobileCompany(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        personMobileCompany_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string person_mobile_company = 7;</code>
       */
      public Builder clearPersonMobileCompany() {
        
        personMobileCompany_ = getDefaultInstance().getPersonMobileCompany();
        onChanged();
        return this;
      }
      /**
       * <code>string person_mobile_company = 7;</code>
       */
      public Builder setPersonMobileCompanyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        personMobileCompany_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object personMobileNumber_ = "";
      /**
       * <code>string person_mobile_number = 8;</code>
       */
      public java.lang.String getPersonMobileNumber() {
        java.lang.Object ref = personMobileNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          personMobileNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string person_mobile_number = 8;</code>
       */
      public com.google.protobuf.ByteString
          getPersonMobileNumberBytes() {
        java.lang.Object ref = personMobileNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          personMobileNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string person_mobile_number = 8;</code>
       */
      public Builder setPersonMobileNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        personMobileNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string person_mobile_number = 8;</code>
       */
      public Builder clearPersonMobileNumber() {
        
        personMobileNumber_ = getDefaultInstance().getPersonMobileNumber();
        onChanged();
        return this;
      }
      /**
       * <code>string person_mobile_number = 8;</code>
       */
      public Builder setPersonMobileNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        personMobileNumber_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Certification)
    }

    // @@protoc_insertion_point(class_scope:Certification)
    private static final org.medibloc.phr.CertificateDataV1.Certification DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.medibloc.phr.CertificateDataV1.Certification();
    }

    public static org.medibloc.phr.CertificateDataV1.Certification getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Certification>
        PARSER = new com.google.protobuf.AbstractParser<Certification>() {
      @java.lang.Override
      public Certification parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Certification(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Certification> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Certification> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.medibloc.phr.CertificateDataV1.Certification getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Certificate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Certificate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Certification_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Certification_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027CertificateDataV1.proto\"a\n\013Certificate" +
      "\022\017\n\007version\030\001 \001(\r\022\032\n\022blockchain_address\030" +
      "\002 \001(\t\022%\n\rcertification\030\003 \001(\0132\016.Certifica" +
      "tion\"\332\001\n\rCertification\022\034\n\024certification_" +
      "result\030\001 \001(\t\022\023\n\013person_name\030\002 \001(\t\022\030\n\020per" +
      "son_birthdate\030\003 \001(\t\022\025\n\rperson_gender\030\004 \001" +
      "(\t\022\025\n\rperson_nation\030\005 \001(\t\022\021\n\tperson_ci\030\006" +
      " \001(\t\022\035\n\025person_mobile_company\030\007 \001(\t\022\034\n\024p" +
      "erson_mobile_number\030\010 \001(\tB%\n\020org.mediblo" +
      "c.phrB\021CertificateDataV1b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Certificate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Certificate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Certificate_descriptor,
        new java.lang.String[] { "Version", "BlockchainAddress", "Certification", });
    internal_static_Certification_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Certification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Certification_descriptor,
        new java.lang.String[] { "CertificationResult", "PersonName", "PersonBirthdate", "PersonGender", "PersonNation", "PersonCi", "PersonMobileCompany", "PersonMobileNumber", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
